### ISSUE TITLE
Multi_GPU problem

### ISSUE THREAD

**Issue by github-cuijian** [RL4VLM/RL4VLM#11]
Hello, I have two 24GB GPUs. When I set `num_processes` to 2 and try to run `run_alf.sh`, the program starts two ALFWorld environments, but eventually exits due to Out Of Memory (OOM). How can I use both cards to run a single process?

**Comment by YX-S-Z** [comment]
Hi, thanks for your question. 

1. As we have mentioned [here](https://github.com/RL4VLM/RL4VLM?tab=readme-ov-file#getting-started), please consider only using one GPU, to avoid the `NCCL runtime error`. 
2. Putting the `NCCL runtime error` aside, you may also want to try to turn on the [q4 quantization](https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO_ALF/scripts/run_alf.sh#L25) to reduce the VRAM. Also you can try to make the [max token length smaller](https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO_ALF/scripts/run_alf.sh#L12) as well. But I suspect it is very hard to make everything below 24G, since we ran our experiments on 80G machines, and without all these tweaks the VRAM at peak are around 35G.

**Comment by Chenhao-Guan** [comment]
Cruious about how many cards used for traing and how long?
