### ISSUE TITLE
Alfworld SFT dataset

### ISSUE THREAD

**Issue by murray-k** [RL4VLM/RL4VLM#12]
How does the tasks in Alfworld SFT dataset map back to the original alfworld/Alfred dataset? I want to run the steps collected in the SFT dataset in the simulator to get reward. But I didn't find a good way to map the task in SFT to the alfworld training/valid dataset. Is it possible that you could add the infos[extra.gamefile] to the SFT dataset? Thanks a lot!!!

**Comment by murray-k** [comment]
Also, a quick question: I saw the images in SFT data starts from step 1, rather than 0. Are these the images/states after executing the first action?

**Comment by YX-S-Z** [comment]
Hello! Thank you for the question and sorry for the late reply:


> Are these the images/states after executing the first action?

This was a naming typo, we accidentally started from the index 1 for saving images. The first image with id 1 should be the initialization, instead of the state after executing the first action.
 
> Is it possible that you could add the infos[extra.gamefile] to the SFT dataset?

Unfortunately, we only ran GPT4-V to play the game and did not save the [extra.gamefile], meaning that recollecting the infos[extra.gamefile] will cost extra money and time. Sorry for the inconvenience.
