### ISSUE TITLE
Some Question about the paper

### ISSUE THREAD

**Issue by Yuxin916** [RL4VLM/RL4VLM#21]
Hi! Thank you for your comprehensive work! 

I have few questions regarding the paper as follows: 

1. In Figure 6 ALFWorld, why the [LLava-sft + RL - CoT](orange curve) training curve is worse than the Figure 5 ALFWorld [pure LLava-sft](purple line) inference? Does that mean without a proper CoT prompt design, the RL training will badly influence the supervised learnt model? 
2. Is the sft dataset/episodes same as the RL training episodes for ALFWorld? Like same trajectory? Or Different? Do you have any intuition on why use GPT-4V to sft the LLaVA first before RL. I intuitively feel like it is similar to behavior cloning at this stage. Then GPT4-V's performance should be the highest boundoury of LLava-sft. If so, why only in Figure 5 EZPoints task, the purple curve (LLava-sft) is higher than red curve (GPT4-V)?
3. In Figure 5 ALFWorld Training curve, the orange one (CNN+RL), and in table 2, the CNN+RL shows all 0 for all tasks? why does that happen? Is it because 5k steps is too short to converge? And more timesteps (normally 200M timesteps for CNN based RL policy) will it have better performance, even outperform the LLaVA-sft one? 

Thanks again and looking forward to your reply. 

Best regards

**Comment by YX-S-Z** [comment]
Hi, thank you for your questions!

1. In Figure 6, the orange curves are SFTed on data without the CoT prompt. I think the takeaway should be: (1) SFT with CoT is better than SFT without CoT; (2) and RL can (slightly) improve upon both cases with and without CoT in alfworld.
2. The intuition for using GPT4-V data to sft LLaVA is to make sure the input prompt & output text are in the correct format. Otherwise LLaVA-1.6 does not always follow the right format (this is because LLaVA-1.6 are not trained on json data), which will create additional challenges for us to post-process the actions. Regarding the difference between alfworld and gym_cards, we have to collect the json instruction following data from gpt4-v because it is unclear how to create such kind of data manually, due to the difficulties in collecting the semantic reasoning CoT. Where as for gym_cards, we can easily generate the CoT based on the current status of the game.
3. CNN + RL achieves 0 on alfworld because CNN fails to learn how to generate a legit phrase. The action space of alfworld is different than gym_cards in the sense that the agent needs to generate an entire legal phrase so that it can go to the next state (See Figure 6). Whereas in gym_cards, randomly selecting a discrete action will lead to a decent performance.

Please let us know if you have more questions!

**Comment by Yuxin916** [comment]
Thank you! That makes a comprehensive clarification! 

Best regards
