### ISSUE TITLE
AL2-Thor window visualization

### ISSUE THREAD

**Issue by Yuxin916** [RL4VLM/RL4VLM#22]
Hi! Thank you for your work!

I just downloaded the sft model of ALFWorld you provided and runing the RL finetuning. I noticed that i could change the env type in the alf-config.yaml. Is it normal to see the AlfredThorEnv Unity Window be open for all time during the RL training? will that slower the training time?

![image](https://github.com/user-attachments/assets/5657379c-0aa3-4af5-8687-7976033196cc)

And especially sometimes it just stuck here for a long while.

Best regards

**Comment by yuslzp** [comment]
I think the solution to it might be listed here https://github.com/alfworld/alfworld/issues/47. I am not sure whether Alfred ThorEnv showed up during our training since we ran it on a remote server, but I would doubt it would slower the training. Could you first try out the solution listed above in the link and see whether the reset would finish? Please update us whether you are able to get it solved.
