### ISSUE TITLE
How to eval?

### ISSUE THREAD

**Issue by GasolSun36** [RL4VLM/RL4VLM#23]
Thanks for your excellent work! However, after reading the code carefully, I did not find any evaluation code, nor the evaluation data. Can you provide the evaluation code? And the evaluation data and its distribution (for example, for the blackjack game, how much test data is there in total)?

**Comment by YX-S-Z** [comment]
Thanks for the question, we are working on providing an evaluation script, please stay tuned!

**Comment by GasolSun36** [comment]
> Thanks for the question, we are working on providing an evaluation script, please stay tuned!

Thanks! Can you just provide the test data ASAP?

**Comment by YX-S-Z** [comment]
To clarify -- we are not running evaluations on the test dataset, everything is evaluated on the environment.

There is no guarantee that we can do that within the timeline you are aiming for, but I can provide some thoughts on the evaluation pipeline, which should be straightforward. Let me know if there are other questions.

1. Initialize the environment (check examples [here](https://github.com/RL4VLM/RL4VLM/blob/main/gym-cards/play_gymcards.ipynb))
2. Pick a VLM you like (it could be calling gpt4-o APIs, or using other open-sourced VLM checkpoint).
3. Write a prompt you like, in fact, you can use any prompt. 
4. Use your prompt to play the game, and then collect multiple trajectories. You may use your own post-processing function from text to action,  you could also consider using our [post-processing function](https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/a2c_ppo_acktr/rl_utils.py#L67) as well.
5. Compute the average success rate.

**Comment by GasolSun36** [comment]
> To clarify -- we are not running evaluations on the test dataset, everything is evaluated on the environment.
> 
> There is no guarantee that we can do that within the timeline you are aiming for, but I can provide some thoughts on the evaluation pipeline, which should be straightforward. Let me know if there are other questions.
> 
> 1. Initialize the environment (check examples [here](https://github.com/RL4VLM/RL4VLM/blob/main/gym-cards/play_gymcards.ipynb))
> 2. Pick a VLM you like (it could be calling gpt4-o APIs, or using other open-sourced VLM checkpoint).
> 3. Write a prompt you like, in fact, you can use any prompt.
> 4. Use your prompt to play the game, and then collect multiple trajectories. You may use your own post-processing function from text to action,  you could also consider using our [post-processing function](https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/a2c_ppo_acktr/rl_utils.py#L67) as well.
> 5. Compute the average success rate.

Hi,

Thanks for your clarify. I I understand the general process, but there are still some small questions:
1. How many trajectories should I collect? For example, should I play like 100 games or 1000 games to calculate the average success rate? I believe there can be a huge different.
2. When playing the game, I assume that each game is different. So if I run the same model (like GPT-4v) for 3 times, Can I get the same results? If so, can you maintain a fair comparison among different models?

Looking forward to your reply! Thanks!

**Comment by YX-S-Z** [comment]
Thank you for the follow-up question. In general, there are no clear standards for each game. Still, during our development, we found that:

1. For Numberline, EZPoints, and Points24, more than 200 trajectories should give you a statistically stable accuracy. 
2. For Blackjack, more than 500 trajectories should make it stable, due to the stochasticity of the game.

Some numbers you may refer -- we did 200 trajectories for Numberline, EZPoints, and Points24. And we did 1000 trajectories on GPT4-V. I would say it should be a fair comparison if you do the same number of evaluations on one task, for all models, and then specify the number of trajectories you have evaluated. 

E.g., you can say something like:
1. For blackjack, we evaluated 1000 trajectories on all models.
2. For other tasks, we evaluated 200 trajectories on all models.

If you are unsure about the statistical stability of different numbers of trajectories to be evaluated, feel free to do another ablation study on the standard deviation on the number of trajectories as well :). I believe this would further improve the quality of your evaluation!
