### ISSUE TITLE
Out of memory suggestions

### ISSUE THREAD

**Issue by Yuxin916** [RL4VLM/RL4VLM#26]
Hi, thanks for your work again! 

I am trying to run the experiment on one 32G GPU, but i noticed here in your previous issue #11 that the peak usage is 35G. But actually the model i am using is just 4B parameters and training variables are lora layers. The out of memory problem still persist (allocate more 508MB). The code will get the OOM error when finish collecting rollouts and doing the PPO update in evaluate action.

Do you have any suggestions in reducing a bit memory? Such as model dtype, quantification, PPO storage rollout device, ....? I am new to this topic and hope could get some advice. 

Thank you!

**Comment by YX-S-Z** [comment]
Hi! Thank you for your interest in our work!

1. Regarding dtype, I think we are using  `float16`, you may refer to our code (here)[https://github.com/RL4VLM/RL4VLM/blob/0f9df2a6995021801bbfeb4c038405124076a391/LLaVA/llava/model/builder.py#L38].
2. You can also try to turn on the q4 quantization we put in the training script, e.g., (here)[https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/scripts/run_bj.sh#L23].
3. I suspect PPO storage is not the major issue, since it only stores a couple of hundred images, which should not take too much vram.


I could be wrong, but I personally suspect there are some other issues when you are loading your models -- since our 7b model only leads to peak performance of < 40G (I think). If I were you, I would try these things in order

1. check how many VRAM it costs to load the model.
2. check whether a smaller (maximum token length)[https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/scripts/run_bj.sh#L10] will make the VRAM better, e.g., you can try 128 or something.

Please let me know if you have other follow-up questions!
